### ISSUE TITLE
Unable to get provider android.support.v4.content.FileProvider

### ISSUE THREAD

**Issue by Rassack** [mike14u/croperino#26]
While trying to integrate cropino I'm getting following error.

java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.gusto.kvartha-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.gusto.kvartha-1, /system/lib]]
                                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5144)
                                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4721)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4661)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5372)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.gusto.kvartha-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.gusto.kvartha-1, /system/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5129)

**Comment by ekimual** [comment]
@Rassack can you provide more information e.g. Device you are using, OS, Code snippet of your integration so I can help
